=== margar1n4o/XML/XML/7MI0700043_Mario_Simeonov_XML_Part2/scripts/schema-definition.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="https://www.w3schools.com"
        xmlns="https://www.w3schools.com"
        elementFormDefault="qualified">
    <xs:element name="tv_programs">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tv_program">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="show">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="title" type="xs:string"/>
                                        <xs:element name="genre" type="xs:string"/>
                                        <xs:element name="description" type="xs:string"/>
                                        <xs:element name="episode">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="episode_number" type="xs:integer"/>
                                                    <xs:element name="air_date" type="xs:date"/>
                                                    <xs:element name="actors">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="actor">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="name" type="xs:string"/>
                                                                            <xs:element name="role" type="xs:string"/>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== margar1n4o/XML/XML/7MI0700043_Mario_Simeonov_XML_Part2/scripts/show2.xml
<?xml version="1.0" encoding="UTF-8" ?>

<tv_programs 
        xmlns="https://www.w3schools.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://www.w3schools.com schema-definition.xsd">
    <tv_program>
        <show>
            <title>Черно зеркало</title>
            <genre>Научна фантастика, Трилър</genre>
            <description>Сериал, изследващ тъмната страна на технологията и нейното влияние върху обществото.</description>
            <episode>
                <episode_number>1</episode_number>
                <air_date>2011-12-04</air_date>
                <actors>
                    <actor>
                        <name>Брайс Далас Хауърд</name>
                        <role>Лейси Паунд</role>
                    </actor>
                    <actor>
                        <name>Алекс Лоутър</name>
                        <role>Кени</role>
                    </actor>
                </actors>
            </episode>
            <episode>
                <episode_number>2</episode_number>
                <air_date>2011-12-11</air_date>
                <actors>
                    <actor>
                        <name>Джоди Уитакър</name>
                        <role>Фифи</role>
                    </actor>
                    <actor>
                        <name>Топър Грейс</name>
                        <role>Джон Бийкър</role>
                    </actor>
                </actors>
            </episode>
        </show>
    </tv_program>
</tv_programs>

=== margar1n4o/XML/XML/7MI0700043_Mario_Simeonov_XML_Part2/scripts/show1.xml
<?xml version="1.0" encoding="UTF-8" ?>

<tv_programs 
        xmlns="https://www.w3schools.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://www.w3schools.com schema-definition.xsd">
    <tv_program>
        <show>
            <title>Шерлок</title>
            <genre>Детектив, Криминален</genre>
            <description>Съвременна адаптация на приключенията на Шерлок Холмс и д-р Джон Уотсън.</description>
            <episode>
                <episode_number>1</episode_number>
                <air_date>2010-07-25</air_date>
                <actors>
                    <actor>
                        <name>Бенедикт Къмбърбач</name>
                        <role>Шерлок Холмс</role>
                    </actor>
                    <actor>
                        <name>Мартин Фрийман</name>
                        <role>Джон Уотсън</role>
                    </actor>
                </actors>
            </episode>
            <episode>
                <episode_number>2</episode_number>
                <air_date>2010-08-01</air_date>
                <actors>
                    <actor>
                        <name>Андрю Скот</name>
                        <role>Мориарти</role>
                    </actor>
                    <actor>
                        <name>Уна Стъбс</name>
                        <role>Госпожа Хъдсън</role>
                    </actor>
                </actors>
            </episode>
        </show>
    </tv_program>
</tv_programs>

=== margar1n4o/XML/XML/7MI0700043_Mario_Simeonov_XML_Part2/scripts/show5.xml
<?xml version="1.0" encoding="UTF-8" ?>

<tv_programs 
        xmlns="https://www.w3schools.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://www.w3schools.com schema-definition.xsd">
    <tv_program>
        <show>
            <title>Бригада</title>
            <genre>Драма, Криминален</genre>
            <description>Сериал за група престъпници в София.</description>
            <episode>
                <episode_number>1</episode_number>
                <air_date>2002-03-10</air_date>
                <actors>
                    <actor>
                        <name>Владимир Пенев</name>
                        <role>Цветан</role>
                    </actor>
                    <actor>
                        <name>Михаил Билалов</name>
                        <role>Део</role>
                    </actor>
                </actors>
            </episode>
            <episode>
                <episode_number>2</episode_number>
                <air_date>2002-03-17</air_date>
                <actors>
                    <actor>
                        <name>Димитър Рачков</name>
                        <role>Коко</role>
                    </actor>
                    <actor>
                        <name>Александър Шопов</name>
                        <role>Звездата</role>
                    </actor>
                </actors>
            </episode>
        </show>
    </tv_program>
</tv_programs>

=== margar1n4o/XML/XML/7MI0700043_Mario_Simeonov_XML_Part2/scripts/show4.xml
<?xml version="1.0" encoding="UTF-8" ?>

<tv_programs 
        xmlns="https://www.w3schools.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://www.w3schools.com schema-definition.xsd">
    <tv_program>
        <show>
            <title>Игра на тронове</title>
            <genre>Фентъзи, Драма</genre>
            <description>Политически и династични борби сред благородни фамилии в Седемте кралства на Вестерос.</description>
            <episode>
                <episode_number>1</episode_number>
                <air_date>2011-04-17</air_date>
                <actors>
                    <actor>
                        <name>Емилия Кларк</name>
                        <role>Дейенерис Таргариен</role>
                    </actor>
                    <actor>
                        <name>Кит Харингтън</name>
                        <role>Джон Сноу</role>
                    </actor>
                </actors>
            </episode>
            <episode>
                <episode_number>2</episode_number>
                <air_date>2011-04-24</air_date>
                <actors>
                    <actor>
                        <name>Лина Хийди</name>
                        <role>Серсеи Ланистър</role>
                    </actor>
                    <actor>
                        <name>Николай Костер-Валдау</name>
                        <role>Джейме Ланистър</role>
                    </actor>
                </actors>
            </episode>
        </show>
    </tv_program>
</tv_programs>

=== margar1n4o/XML/XML/7MI0700043_Mario_Simeonov_XML_Part2/scripts/show3.xml
<?xml version="1.0" encoding="UTF-8" ?>

<tv_programs 
        xmlns="https://www.w3schools.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://www.w3schools.com schema-definition.xsd">
    <tv_program>
        <show>
            <title>Приятели</title>
            <genre>Комедия</genre>
            <description>Група приятели в Ню Йорк.</description>
            <episode>
                <episode_number>1</episode_number>
                <air_date>1994-09-22</air_date>
                <actors>
                    <actor>
                        <name>Дженифър Анистън</name>
                        <role>Рейчъл Грийн</role>
                    </actor>
                    <actor>
                        <name>Кортни Кокс</name>
                        <role>Моника Гелър</role>
                    </actor>
                </actors>
            </episode>
            <episode>
                <episode_number>2</episode_number>
                <air_date>1994-09-29</air_date>
                <actors>
                    <actor>
                        <name>Дейвид Шуимър</name>
                        <role>Рос Гелър</role>
                    </actor>
                    <actor>
                        <name>Лийза Кудроу</name>
                        <role>Фийби Буфе</role>
                    </actor>
                </actors>
            </episode>
        </show>
    </tv_program>
</tv_programs>
